apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "githubapp.fullname" . }}
  labels:
    {{- include "githubapp.labels" . | nindent 4 }}
spec:
  endpoints:
    - port: http
      path: /metrics
  selector:
    matchLabels:
      {{- include "githubapp.selectorLabels" . | nindent 6 }}
