# Production environment overrides
image:
  repository: quay.io/wire/github-app
  tag: "sha-3a9c9d7"
ingress:
  enabled: true
  className: nginx
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt
  hosts:
  - host: github-app.apps-prod.wire.com
    paths:
    - path: /
      pathType: Prefix
  tls:
  - hosts:
    - github-app.apps-prod.wire.com
    secretName: github-app-tls
env:
- name: WIRE_SDK_API_HOST
  value: "https://prod-nginz-https.wire.com"
- name: GHAPP_API_HOST
  value: "https://github-app.apps-prod.wire.com"
- name: GHAPP_SERVER_PORT
  value: "8080"
